#!/usr/bin/env python3
#?pyuic5 -x coursework.ui -o cw1.py
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coursework.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cw2 import Ui_Form

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 600)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("border-top-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 54, 255);\n"
"background-color: rgb(22, 170, 223);\n"
"selection-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
       # MainWindow.setStyleSheet("background-image: url('./background.jpg');\n")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 20, 231, 21))
        self.label_7.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_7.setText("<html><head/><body><p align=\"center\"><span style=\" font-family:\'Liberation Serif,serif\'; font-size:14pt; font-weight:600; color:#ffffff;\">Положительные критерии</span></p></body></html>")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_7.setObjectName("label_7")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 490, 141, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 591, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Объем предоставляемых услуг</span></p></body></html>")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_3.setText("<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Уровень защиты данных</span></p></body></html>")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_5.setFrame(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_6.setFrame(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout.addWidget(self.comboBox_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionRecent_2 = QtWidgets.QAction(MainWindow)
        self.actionRecent_2.setObjectName("actionRecent_2")
        self.menuOpen.addAction(self.actionRecent_2)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionReplace)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.secondscr)   
       

    def secondscr(self, out):
        index1 = self.comboBox.currentIndex()
        if index1 == 1:
            out= out+ 16
        elif index1 == 2:
            out= out+ 8 
        elif index1 ==3:
            out= out+ 0
                
        index2 = self.comboBox_2.currentIndex()
        if index2 == 1:
            out= out+ 16
        elif index2 == 2:
            out= out+ 8  
        elif index2 ==3:
            out= out+ 0

        index3 = self.comboBox_3.currentIndex()
        if index3 == 1:
            out= out+ 16
        elif index3 == 2:
            out= out+ 8  
        elif index3 ==3:
            out= out+ 0
                
        index4 = self.comboBox_4.currentIndex()
        if index4 == 1:
            out= out+ 16
        elif index4 == 2:
            out= out+ 8    
        elif index4 ==3:
            out= out+ 0
        
        index5 = self.comboBox_5.currentIndex()
        if index5 == 1:
            out= out+ 16
        elif index5 == 2:
            out= out+ 8  
        elif index5 ==3:
            out= out + 0

        index6 = self.comboBox_6.currentIndex()
        if index6 == 1:
            out= out+ 0
        elif index6 == 2:
            out= out+ 7    
        elif index6 ==3:
            out= out+ 14   
        elif index6 == 4 :
            out= out+ 20
       

        
        self.pushButton.setText(str(out))
        
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
        return out
   
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Evaluator"))
        self.pushButton.setText(_translate("MainWindow", "NEXT"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Локализация ИС</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Реализация удаленного доступа</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Обратная связь</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Качества поддержки</span></p></body></html>"))
        
        self.comboBox.setItemText(0, _translate("MainWindow", "Выберите"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Обширный"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Полный"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Неполный"))
        #self.comboBox.addItem("7")

        self.comboBox_2.setItemText(0, _translate("MainWindow", "Выберите"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Надежная"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Частичная"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Отсутствие"))

        self.comboBox_3.setItemText(0, _translate("MainWindow", "Выберите"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Строго регламентированный"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Чувствительный"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Базовый уровень"))

        self.comboBox_4.setItemText(0, _translate("MainWindow", "Выберите"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Немедленный доступ"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Доступ к конечной точке"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Неэффективный доступ"))

        self.comboBox_5.setItemText(0, _translate("MainWindow", "Выберите"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Реальные отзывы"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Сомнительная система"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Нет отзывов"))

        self.comboBox_6.setItemText(0, _translate("MainWindow", "Выберите"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Нет поддержки"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Реализация одного варианта"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Реализация двух вариантов"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "Многовариантная реализация"))

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionReplace.setText(_translate("MainWindow", "Replace"))
        self.actionReplace.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionRecent.setText(_translate("MainWindow", "Recent"))
        self.actionRecent_2.setText(_translate("MainWindow", "Recent"))
# import coursework_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
