#!/usr/bin/env python3
# # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coursework2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 600)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        Form.setFont(font)
        Form.setStyleSheet("border-top-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 54, 255);\n"
"background-color: rgb(22, 173, 223);\n"
"selection-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(250, 30, 231, 21))
        self.label_13.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_13.setText("<html><head/><body><p align=\"center\"><span style=\" font-family:\'Liberation Serif,serif\'; font-size:14pt; font-weight:600; color:#ffffff;\">Отрицательные критерии</span></p></body></html>")
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(True)
        self.label_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 520, 141, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 490, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(350, 510, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(490, 510, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(130, 80, 271, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_8.setText("<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Сложность интерфейса</span></p></body></html>")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(True)
        self.label_8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_12.setText("<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Административность ресурса</span></p></body></html>")
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(True)
        self.label_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(400, 60, 271, 401))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setKerning(True)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setAutoFillBackground(False)
        self.comboBox_7.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_7)
        self.comboBox_10 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_10.setFont(font)
        self.comboBox_10.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_10)
        self.comboBox_8 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_8.setFont(font)
        self.comboBox_8.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_8)
        self.comboBox_11 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_11.setFont(font)
        self.comboBox_11.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_11)
        self.comboBox_9 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        self.comboBox_9.setFont(font)
        self.comboBox_9.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_9.setFrame(True)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.result)
        

    def result(self, out):
        index7 = self.comboBox_7.currentIndex()
        if index7 == 1:
            out = out + 0
        elif index7 == 2:
            out = out - 10     
        elif index7 ==3:
            out = out - 20
                
        index8 = self.comboBox_8.currentIndex()
        if index8 == 1:
            out= out+ 0
        elif index8 == 2:
            out= out- 10     
        elif index8 ==3:
            out= out- 20

        index9 = self.comboBox_9.currentIndex()
        if index9 == 1:
            out= out+ 0
        elif index9 == 2:
            out= out- 10     
        elif index9 ==3:
            out= out- 20
                
        index10 = self.comboBox_10.currentIndex()
        if index10 == 1:
            out= out+ 0
        elif index10 == 2:
            out= out- 10     
        elif index10 ==3:
            out= out- 20
        
        index11 = self.comboBox_11.currentIndex()
        if index11 == 1:
            out= out+ 0
        elif index11 == 2:
            out= out- 10     
        elif index11 ==3:
            out= out- 20
        self.label_3.setText(str(out) + "%")
        return out
       
    
       
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Evaluator"))
        self.pushButton.setText(_translate("Form", "RUN"))
        self.label.setText(_translate("Form", "Результат вычисления"))
        self.label_2.setText(_translate("Form", "Вывод по ресурсу:"))
        value = self.comboBox_7.currentText()
        # self.label_3.setText(_translate("Form","0%"))
        
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Наличие ненужной информации</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Наличие гарантии</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'Liberation Serif,serif\'; font-weight:600; color:#ffffff;\">Приемлемость модификации</span></p></body></html>"))
        
        self.comboBox_7.setItemText(0, _translate("Form", "Выберите"))
        self.comboBox_7.setItemText(1, _translate("Form", "Удобный интерфейс"))
        self.comboBox_7.setItemText(2, _translate("Form", "Неадаптированный интерфейс"))
        self.comboBox_7.setItemText(3, _translate("Form", "Сложный интерфейс"))
        
        self.comboBox_10.setItemText(0, _translate("Form", "Выберите"))
        self.comboBox_10.setItemText(1, _translate("Form", "Нет ненужной информации"))
        self.comboBox_10.setItemText(2, _translate("Form", "Небольшое количество "))
        self.comboBox_10.setItemText(3, _translate("Form", "Неадаптированная информация"))
      
        self.comboBox_8.setItemText(0, _translate("Form", "Выберите"))
        self.comboBox_8.setItemText(1, _translate("Form", "Администрируется"))
        self.comboBox_8.setItemText(2, _translate("Form", "Не часто вводится"))
        self.comboBox_8.setItemText(3, _translate("Form", "Крайне редко администрируется"))
      
        self.comboBox_11.setItemText(0, _translate("Form", "Выберите"))
        self.comboBox_11.setItemText(1, _translate("Form", "Без гарантии"))
        self.comboBox_11.setItemText(2, _translate("Form", "Не детализированный"))
        self.comboBox_11.setItemText(3, _translate("Form", "Гарантия с полным описанием"))
      
        self.comboBox_9.setItemText(0, _translate("Form", "Выберите"))
        self.comboBox_9.setItemText(1, _translate("Form", "Идеально выполненный"))
        self.comboBox_9.setItemText(2, _translate("Form", "Приемлемый"))
        self.comboBox_9.setItemText(3, _translate("Form", "Неприемлемо"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
