# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fincalc2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 312)
        MainWindow.setStyleSheet("selection-background-color: rgb(0, 54, 255);\n"
"background-color: rgb(22, 173, 223);\n"
"selection-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(350, 260, 80, 29))
        self.run.setObjectName("run")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 131, 29))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(12)
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setMouseTracking(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 70, 113, 29))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 87, 83);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 120, 113, 29))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 87, 83);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 170, 113, 29))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 87, 83);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 210, 151, 29))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 87, 83);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(240, 260, 80, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.run.clicked.connect(self.func)
        self.clear.clicked.connect(self.clearer)

    def func(self):
            amount = int(self.lineEdit.text())
            day = int(self.lineEdit_2.text())
            interest = int(self.lineEdit_3.text())
            index1 = self.comboBox.currentIndex()
            if index1 == 0:
                calculation = amount*(1+(interest/100)*(day/365))
                calculation = round(calculation,2)
            elif index1 == 1:
                calculation = amount*(1+(interest*0.01/365)**(day/365))
                calculation = round(calculation,2)
            self.lineEdit_4.setText(str(calculation)+ "₽")
  
    def clearer(self):
            self.lineEdit.clear()
            self.lineEdit_2.clear()
            self.lineEdit_3.clear()
            self.lineEdit_4.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Loan Calculator"))
        self.label.setText(_translate("MainWindow", "Тип расчета"))
        self.label_2.setText(_translate("MainWindow", "Сумма кредита"))
        self.label_3.setText(_translate("MainWindow", "Процентная ставка"))
        self.label_4.setText(_translate("MainWindow", "Период (в днях)"))
        self.label_5.setText(_translate("MainWindow", "Сумма, подлежащая возврату "))
        self.run.setText(_translate("MainWindow", "RUN"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Простая"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Сложная"))
        self.clear.setText(_translate("MainWindow", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
